sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
node_js:
- '14'
cache:
- node_modules
install:
- npm install
script:
- npm run lint
- npm run build
- npm run coverage
