sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
node_js:
- '14'
cache:
- node_modules
before_install:
  - export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
  - export COVERALLS_SERVICE_NAME="ckeditor/ckeditor5-react code coverage"
install:
- npm install
script:
- npm run lint
- npm run build
- npm run coverage
- cat coverage/*/lcov.info | ./node_modules/.bin/coveralls
