minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - protobufjs

overrides:
  '@ckeditor/ckeditor5-integrations-common': link:../../../.local/share/pnpm/global/5/node_modules/@ckeditor/ckeditor5-integrations-common
  diff@^7: ^8.0.3
  semver: ^7.0.0
  serialize-javascript@^6: ^7.0.3

preferFrozenLockfile: true

shamefullyHoist: true

shellEmulator: true
