onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - protobufjs

overrides:
  'diff@^7': '^8.0.3'
  'serialize-javascript@^6': '^7.0.5'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'
  - 'basic-ftp' # Remove after 2026-04-11.
  - 'vite' # Remove after 2026-04-09.

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
